AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2BuildMachine:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0a8b4cd432b1c3063"
      InstanceType: "t2.micro"
      InstanceInitiatedShutdownBehavior: "stop"
      IamInstanceProfile: "LabInstanceProfile"
      KeyName: "<ssh_key_name>"
      SecurityGroups:
        - !Ref EC2SshSecurityGroup
Outputs:
  EC2BuildMachine:
    Description: "Machine Created"
    Value: !Ref EC2BuildMachine
